protected/controllers/LoginController.php
<?php

class LoginController extends Controller {
    
    protected function _saveTwiConnect() {
        /* If access tokens are not available redirect to connect page. */
        if (empty(Yii::app()->session['access_token']) || empty(Yii::app()->session['access_token']['oauth_token']) || empty(Yii::app()->session['access_token']['oauth_token_secret'])) {
            $this->redirect(array('login/clearsessions'));
        } else {
            $identity = new UserIdentityTwi();
            $identity->authenticate();
            
            if ($identity->errorCode === UserIdentity::ERROR_NONE){
                $duration = 3600 * 24 * 30; // 30 days
                Yii::app()->user->login($identity, $duration);
                $this->redirect(Yii::app()->user->returnUrl);
            }
        }
    }
    
    public function actionIndex(){
        return $this->actionLogin();
    }
    
    public function actionCallback() {
        /* If the oauth_token is old redirect to the connect page. */
        if (isset($_REQUEST['oauth_token']) && Yii::app()->session['oauth_token'] !== $_REQUEST['oauth_token']) {
            Yii::app()->session['oauth_status'] = 'oldtoken';
            $this->redirect(array('login/clearsessions'));
        }

        /* Create TwitteroAuth object with app key/secret and token key/secret from default phase */
        $connection = new twitteroauth(
                Yii::app()->params['private']['CONSUMER_KEY'], 
                Yii::app()->params['private']['CONSUMER_SECRET'], 
                Yii::app()->session['oauth_token'], 
                Yii::app()->session['oauth_token_secret']);

        /* Request access tokens from twitter */
        if (empty($_REQUEST['oauth_verifier'])){
            $this->redirect(array('login/clearsessions'));
            return;
        }
        $access_token = $connection->getAccessToken($_REQUEST['oauth_verifier']);

        /* Save the access tokens. Normally these would be saved in a database for future use. */
        Yii::app()->session['access_token'] = $access_token;

        /* Remove no longer needed request tokens */
        unset(Yii::app()->session['oauth_token']);
        unset(Yii::app()->session['oauth_token_secret']);

        /* If HTTP response is 200 continue otherwise send to connect page to retry */
        if (200 == $connection->http_code) {
            /* The user has been verified and the access tokens can be saved for future use */
            Yii::app()->session['status'] = 'verified';
            $this->_saveTwiConnect();
        } else {
            /* Save HTTP status for error dialog on connnect page. */
            $this->redirect(array('login/clearsessions'));
        }
    }
    
    
    public function actionClearsessions() {
        unset(Yii::app()->session['oauth_token'], Yii::app()->session['oauth_token_secret'], Yii::app()->session['status']);
        $this->redirect(Yii::app()->homeUrl);
    }
    
    public function actionTwi() {
        /* Build TwitterOAuth object with client credentials. */
        $connection = new twitteroauth(Yii::app()->params['private']['CONSUMER_KEY'], Yii::app()->params['private']['CONSUMER_SECRET']);

        /* Get temporary credentials. */
        $request_token = $connection->getRequestToken($this->createAbsoluteUrl('login/callback'));

        /* Save temporary credentials to session. */
        Yii::app()->session['oauth_token'] = $token = $request_token['oauth_token'];
        Yii::app()->session['oauth_token_secret'] = $request_token['oauth_token_secret'];

        /* If last connection failed don't display authorization link. */
        switch ($connection->http_code) {
            case 200:
                /* Build authorize URL and redirect user to Twitter. */
                $url = $connection->getAuthorizeURL($token);
                header('Location: ' . $url);
                break;
            default:
                Yii::log('Invalid response from Twitter: ' . $connection->http_code . '; ' . json_encode($connection), CLogger::LEVEL_ERROR, 'AUTH');
                /* Show notification if something went wrong. */
                echo 'Could not connect to Twitter. Refresh the page or try again later.';
        }
    }
    
    public function actionLogout() {
        unset(Yii::app()->session['oauth_token'], Yii::app()->session['oauth_token_secret']);
        Yii::app()->user->logout();
        $this->redirect(Yii::app()->homeUrl);
    }
    
    public function actionLogin(){
        $oauth2LoginReturnUrl = Yii::app()->user->getState('oauth2LoginReturnUrl');
        if ($oauth2LoginReturnUrl){
            Yii::app()->user->returnUrl = $oauth2LoginReturnUrl;
            Yii::app()->user->setState('oauth2LoginReturnUrl', null);
        }
        
        $this->render('selectProvider', array(
            'isGuest' => Yii::app()->user->isGuest,
            'canConnectTwi' => (!Yii::app()->user->isGuest && !Yii::app()->user->getModel()->external_id_twi),
            'canConnectVk' => (!Yii::app()->user->isGuest && !Yii::app()->user->getModel()->external_id_vk),
        ));
    }
    
    public function actionVK() {
        $authIdentity = Yii::app()->eauth->getIdentity('vkontakte');
        $authIdentity->redirectUrl = Yii::app()->user->returnUrl;
        $authIdentity->cancelUrl = $this->createAbsoluteUrl('login/selectProvider');

        if ($authIdentity->authenticate()) {
            $identity = new UserIdentityVK($authIdentity);
            
            if ($identity->authenticate()) {
                $duration = 3600 * 24 * 30; // 30 days
                Yii::app()->user->login($identity, $duration);

                // special redirect with closing popup window
                $authIdentity->redirect();
            } else {
                // close popup window and redirect to cancelUrl
                $authIdentity->cancel();
            }
        }

        // Something went wrong, redirect to login page
        $this->redirect(array('login/selectProvider'));
    }
}

protected/controllers/UsersController.php
<?php

class UsersController extends Controller {

    public $userName;
    
    public function actionById($userId){
        $user = User::model()->find('id = :id', array(':id' => $userId));
        $this->actionView($user);
    }
    
    public function actionByName($userName){
        $user = User::model()->find('screen_name LIKE :userName', array(':userName' => $userName));
        $this->actionView($user);
    }

    public function actionView($user) {
        if ($user) {
            $this->userName = $user->screen_name;
            $criteria = new CDbCriteria();
            $criteria->condition = 'ach_approved_date IS NOT NULL AND status = ' . UserAchievement::STATUS_APPROVED;
            $achievedCount = Achievement::model()->achievedByUser($user)->public()->count($criteria);
            $achievedPages = new CPagination($achievedCount);
            $achievedPages->pageVar = 'achPage';
            $achievedPages->pageSize = 10;
            $achievedPages->params = $_GET;
            $criteria->order = 'ach_date DESC';
            unset($achievedPages->params['addedPage']);
            $achievedPages->applyLimit($criteria);
            $achievedList = Achievement::model()->achievedByUser($user)->public()->findAll($criteria);

            $criteria2 = new CDbCriteria();
            $addedCount = Achievement::model()->addedByUser($user)->public()->count($criteria2);
            $addedPages = new CPagination($addedCount);
            $addedPages->pageVar = 'addedPage';
            $addedPages->pageSize = 10;
            $addedPages->params = $_GET;
            $criteria2->order = 'ins_date DESC';
            unset($addedPages->params['achPage']);
            $addedPages->applyLimit($criteria2);
            $addedList = Achievement::model()->addedByUser($user)->public()->findAll($criteria2);

            $activeTab = 'achievedList';
            if (!empty($_GET['addedPage'])) {
                $activeTab = 'addedList';
            }

            $this->render('view', array(
                'user' => $user,
                'viewUser' => User::model()->findByPk(Yii::app()->user->getId()),
                'achievedList' => $achievedList,
                'achievedPages' => $achievedPages,
                'achievedCount' => $achievedCount,
                'addedList' => $addedList,
                'addedPages' => $addedPages,
                'addedCount' => $addedCount,
                'activeTab' => $activeTab,
            ));
        } else {
            throw new CHttpException(404, 'Такой пользователь не найден.');
        }
    }

    public function actionInstallRoles() {

        if (Yii::app()->user->getModel()->external_id_twi != '115622071'){
            throw new CHttpException(403,'Forbidden');
        }
        
        $auth = Yii::app()->authManager;

        //сбрасываем все существующие правила
        $auth->clearAll();
        
        $task = $auth->createTask('userManage', 'управление пользователями');
        $auth->createOperation('grantModeration', 'сделать модератором');
        $auth->createOperation('revokeModeration', 'отобрать модераторорство');
        $auth->createOperation('banUser', 'заблокировать пользователя');
        $task->addChild('grantModeration');
        $task->addChild('revokeModeration');
        $task->addChild('banUser');
        
        $task = $auth->createTask('approveAchieve', 'подтверждение достижения');
        $auth->createOperation('approve', 'принять');
        $auth->createOperation('reject', 'отклонить');
        $task->addChild('approve');
        $task->addChild('reject');
        
        $auth->createOperation('addAchievement', 'добавить достижение');
        $auth->createOperation('deleteAnyAchievement', 'удалить любое достижение');
        
        
        $bizRule='return Yii::app()->user->checkAccess("deleteAnyAchievement") 
            || (Yii::app()->user->id==$params["achievement"]->author_id && $params["achievement"]->isAbleToSafeDeleted());';
        $auth->createOperation('deleteAchievement', 'удалить достижение', $bizRule);
        
        $auth->createRole('guest');
        
        $role = $auth->createRole('user');
        $role->addChild('addAchievement');
        $role->addChild('deleteAchievement');
        
        $role = $auth->createRole('moderator');
        $role->addChild('user');
        $role->addChild('approveAchieve');
        
        $role = $auth->createRole('admin');
        $role->addChild('moderator');
        $role->addChild('userManage');
        $auth->createOperation('approveMyAchieve', 'подтверждать свои достижения');
        $role->addChild('approveMyAchieve');
        $role->addChild('deleteAnyAchievement');
        
        //связываем пользователя с ролью
        //$auth->assign('admin', 2);
        
        $auth->save();
        
        echo 'Done.';
    }
    
    public function actionTop(){
        $list = User::getTopList();
        
        $this->render('top', array(
            'users'=>$list
                ));
    }

    public function actionBan(){
        if (!Yii::app()->user->checkAccess('banUser')) {
            throw new CHttpException(403, 'Forbidden');
        }
        $model = User::model()->findByPk($_REQUEST['userid']);
        
        if ($model && !empty($_POST['confirm'])){
            $model->ban();
            $this->redirect(Yii::app()->homeUrl);
        }
        
        $this->render('confirmBan', array('model'=>$model));
    }
    
    public function actionBanned(){
        if (Yii::app()->user->getModel()->banned) {
            unset(Yii::app()->session['oauth_token'], Yii::app()->session['oauth_token_secret']);
            Yii::app()->user->logout();
            $this->render('banned');
        } else {
            $this->redirect(Yii::app()->homeUrl);
        }
    }
    
    public function actionApps(){
        if (!Yii::app()->user->isGuest){
            
            $models = Yii::app()->user->getModel()->userApps(
                    array('condition'=>'grant_status = :st', 
                        'params'=>array(':st'=>UserApp::GRANT_STATUS_GRANTED)
                        ));
            
            $myApps = AppOAuth::model()->findAll('app_owner_user_id=:uid', array(':uid'=>Yii::app()->user->getId()));
            
            $this->render('apps', array(
                'models'=>$models,
                'myApps'=>$myApps,
                ));
            
        } else {
            $this->redirect('/login/index');
        }
    }
    
    public function actionRevokeApp(){
        $appId = $_GET['appId'];
        if ($appId){
            Yii::app()->user->getModel()->revokeApp($appId);
            Yii::app()->user->setFlash('success', '<strong>Приложению убран доступ!</strong>.');
            $this->redirect(array('users/apps'));
        }
    }
}

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<!DOCTYPE html>  
<html>  
    <head>  
        <meta charset="utf-8">  
        <title><?php echo CHtml::encode($this->pageTitle); ?></title> 
        <?php Yii::app()->bootstrap->register(); ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">  
        <link rel="shortcut icon" href="/images/favicon.ico">
        <meta name="description" content="Как много вы добились?">        
        <link rel="stylesheet" type="text/css" href="<?=$this->assetsCssBase?>/main.css" />
        <?Yii::app()->clientScript->registerScriptFile($this->assetsJsBase.'/main.js')?>
    </head>  
    <body>  
        <div class="navbar navbar-fixed-top title-nav">  
            <div class="navbar-inner">  
                <div class="container">  
                    <a class="brand" href="<?=Yii::app()->homeUrl?>"><?php echo CHtml::encode(Yii::app()->name); ?></a>  
                    <div>  
                        <?php
                        $mainMenuItems = array(
                            array('label' => 'Достижения', 'url' => array('/achievement/index')),
                            array('label' => 'Добавить достижение', 'url' => array('/achievement/add')),
                            array('label' => 'Топ', 'url' => array('/users/top')),
                        );
                        if (!Yii::app()->user->isGuest){
                            $active = false;
                            if ($this->id == 'users' && Yii::app()->user->name == $this->userName){
                                $active = true;
                            }
                            $mainMenuItems[] = array('label' => 'Мой профиль', 'url' => array('/user/' . Yii::app()->user->getModel()->screen_name), 'active'=>$active);
                        }
                        
                        if (Yii::app()->user->checkAccess('approveAchieve')){
                            $count = UserAchievement::countForApprove();
                            if ($count){
                                $countLabel = " ($count)";
                            } else {
                                $countLabel = '';
                            }
                            $mainMenuItems[] = array('label' => 'Модерирование'.$countLabel, 'url' => array('/achievement/approve'));
                        }
                        
                        $this->widget('bootstrap.widgets.TbMenu', array(
                            'items' => $mainMenuItems,
                        ));
                        ?>
                        
                        <ul id="yw1" class="pull-right nav">
                            <?php if (Yii::app()->user->isGuest) { ?>
                                <li><a href="<?= $this->createUrl('/login/index')?>">Войти</a></li>
                            <? } else { ?>
                                <li class="dropdown">
                                    <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                                        <img title="<?= Yii::app()->user->name ?>" alt="<?= Yii::app()->user->name ?>" src="<?=Yii::app()->user->getModel()->profile_image_url?>">
                                        <span class="avatar" title="Уровень <?=Yii::app()->user->getModel()->level?>"><?= Yii::app()->user->name ?><?if (Yii::app()->user->getModel()->level) echo "<sup>".Yii::app()->user->getModel()->level."</sup>"; ?></span> <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?= $this->createUrl('/login/login')?>" tabindex="-1">Подключить другие сервисы</a></li>
                                        <li><a href="<?= $this->createUrl('/users/apps')?>" tabindex="-1">Приложения</a></li>
                                        <li><a href="<?= $this->createUrl('/login/logout')?>" tabindex="-1">Выйти</a></li>
                                    </ul>
                                </li>
                            <?php } ?>
                        </ul>
                        
                        <?php 
                        if (!Yii::app()->user->isGuest) {
                            $curPoints = Yii::app()->user->getModel()->countPoints();
                            $level = Yii::app()->user->getModel()->level;
                            $leftBoundPoints = User::getAmountPointsForLevel($level);
                            $rightBoundPoints = UseR::getAmountPointsForLevel($level + 1);
                            $rightBoundPointsLevel = $rightBoundPoints - $leftBoundPoints;
                            $curPointsLevel = $curPoints - $leftBoundPoints;  
                            $percent = round($curPointsLevel / $rightBoundPointsLevel * 100);
                            ?> 
                                <div class="progress user-level-progress span2 pull-right" title="Прогресс вашего уровня: <?= $curPoints ?>/<?= $rightBoundPoints ?>">
                                    <div class="bar" style="width: <?=$percent?>%;"><?= $curPointsLevel ?>/<?= $rightBoundPointsLevel ?></div>
                                </div>
                        <?php } ?>
                        
                    </div><!--/.nav-collapse -->  
                </div>  
            </div>  
        </div>
        
        
        
        <div class="container">  
            
            <?php if (isset($this->breadcrumbs)): ?>
                <?php
                $this->widget('bootstrap.widgets.TbBreadcrumbs', array(
                    'links' => $this->breadcrumbs,
                ));
                ?><!-- breadcrumbs -->
            <?php endif ?>
                
            <div class="row">
                <div class="span12">
                    <?php echo $content; ?>
                </div>
            </div>
            
            <hr>  
            <footer>  
                <p>© <a href="https://twitter.com/LiveLevelNet" target="_blank">Livelevel.net</a> 2013.</p>
                <p><?=CHtml::link('Правила', array('/site/page/view/rules'))?></p>
                <p><?=CHtml::link('Разработчикам', array('/dev'))?></p>  
            </footer>  
        </div> <!-- /container -->  
        <?php if (!(defined('YII_DEBUG') && YII_DEBUG)) { ?>
        <!-- Yandex.Metrika counter -->
        <script type="text/javascript">
        (function (d, w, c) {
            (w[c] = w[c] || []).push(function() {
                try {
                    w.yaCounter20560975 = new Ya.Metrika({id:20560975,
                            clickmap:true,
                            trackHash:true});
                } catch(e) { }
            });

            var n = d.getElementsByTagName("script")[0],
                s = d.createElement("script"),
                f = function () { n.parentNode.insertBefore(s, n); };
            s.type = "text/javascript";
            s.async = true;
            s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

            if (w.opera == "[object Opera]") {
                d.addEventListener("DOMContentLoaded", f, false);
            } else { f(); }
        })(document, window, "yandex_metrika_callbacks");
        </script>
        <noscript><div><img src="//mc.yandex.ru/watch/20560975" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
        <!-- /Yandex.Metrika counter -->
        <?php } ?>
    </body>  
</html>