protected/models/User.php
<?php

/*
 * The followings are the available model relations:
 * @property Achievement[] $achievementsAuthor
 * @property Achievement[] $achievementsApprover
 * @property UserAchievement[] $userAchievements
 * @property UserPoints[] $userPoints
 * @property UserApp[] $userApps
 * @property AppOAuth[] $ownedApps
 */

class User extends CActiveRecord {
    
    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'user';
    }
    
    public function rules() {
        return array(
            array('external_id, screen_name, profile_image_url, name, lang, location', 'safe'),
        );
    }
    
    
    public function getProfileUrl(){
        return Yii::app()->createUrl('/user/' . CHtml::encode($this->id) . '/' . CHtml::encode($this->screen_name));
    }
    
    /**
     * @return array relational rules.
     */
    public function relations()
    {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
            'achievementsAuthor' => array(self::HAS_MANY, 'Achievement', 'author_id'),
            'achievementsApprover' => array(self::HAS_MANY, 'Achievement', 'approved_by'),
            'userAchievements' => array(self::HAS_MANY, 'UserAchievement', 'iduser'),
            'userPoints' => array(self::HAS_MANY, 'UserPoints', 'iduser'),
            'ownedApps' => array(self::HAS_MANY, 'AppOAuth', 'app_owner_user_id'),
            'userApps' => array(self::HAS_MANY, 'UserApp', 'iduser'),
        );
    }
    
    public function addPoints($points, $action, $idach = null){
        $up = new UserPoints;
        $up->iduser = $this->id;
        $up->points = intval($points);
        $up->action = $action;
        if ($idach){
            $up->idach = $idach;
        }
        $up->save();
    }
    
    public function countPoints() {
        $points = Yii::app()->db->createCommand()
                ->select('SUM(points)')
                ->from('user_points')
                ->where('iduser=:iduser', array(':iduser' => $this->id))
                ->queryScalar();
        return (int)$points;
    }
    
    public function updateCurrentLevel() {
        $points = $this->countPoints();
        for ($i = 0; $i < 50; $i++) {
            if (self::getAmountPointsForLevel($i) > $points) {
                break;
            }
        }
        $lvl = max($i - 1, 0);
        $this->points = $points;
        $this->level = $lvl;
        $this->save();
    }
    
    public static function getAmountPointsForLevel($lvl){
        if ($lvl == 0){
            return 0;
        }
        $amount = 30;
        for ($i=1; $i < $lvl; $i++){
            $amount += round( pow(2*$i + 8, 1.5) );
        }
        return (int) $amount;
    }
    
    public static function getTopList(){
        $criteria = new CDbCriteria();
        $criteria->limit = 50;
        $criteria->condition = "level > 0 AND ((role IS NULL) OR (role!='admin' AND role!='moderator'))";
        $criteria->order = 'level DESC, points DESC, ins_date';
        return User::model()->findAll($criteria);
    }
    
    public function countAchievedAndProoved(){
        $criteria = new CDbCriteria();
        $criteria->condition = 'ach_approved_date IS NOT NULL AND iduser = :iduser AND status = ' . UserAchievement::STATUS_APPROVED;
        $criteria->params = array(':iduser'=>$this->id);
        return UserAchievement::model()->count($criteria);
    }
    
    public function ban(){
        $this->banned = 1;
        $this->save();
    }
    
    public function getHash(){
        return md5($this->screen_name . ':' . $this->id . 'confirmSalt_');
    }
    
    public function getExternalProfileUrl(){
        if ($this->external_id_twi){
            return 'https://twitter.com/' . $this->screen_name;
        } else if ($this->external_id_vk){
            return 'https://vk.com/' . $this->screen_name;
        }
    }
    
    public function grantApp($idClient){
        if ($this->checkGrantApp($idClient)){
            return;
        }
        $uapp = new UserApp;
        $uapp->client_id = $idClient;
        $uapp->iduser = $this->id;
        $uapp->grant_status = UserApp::GRANT_STATUS_GRANTED;
        $uapp->grant_date = new CDbExpression('NOW()');
        $uapp->save();
    }
    
    public function checkGrantApp($idClient){
        $res = UserApp::model()->exists('iduser=:iduser AND client_id=:client_id AND grant_status=:grant_status', 
                array(
                    ':iduser'=>$this->id,
                    ':client_id'=>$idClient,
                    ':grant_status'=>UserApp::GRANT_STATUS_GRANTED,
                    ));
        return $res;
    }
    
    public function revokeApp($idClient){
        $uapp = UserApp::model()->find('iduser=:iduser AND client_id=:client_id AND grant_status=:grant_status', 
                array(
                    ':iduser'=>$this->id,
                    ':client_id'=>$idClient,
                    ':grant_status'=>UserApp::GRANT_STATUS_GRANTED,
                    ));
            if ($uapp) {
            $uapp->grant_status = UserApp::GRANT_STATUS_NONE;
            $uapp->save();

            //delete all user's tokens
            $command = Yii::app()->db->createCommand();
            $command->delete('oauth2_tokens', 'user_id=:user_id AND client_id=:client_id', array(':user_id'=>$this->id, ':client_id'=>$idClient));
        }
    }
    
    public function behaviors() {
        return array(
            'ApiStdModelBehavior' => array(
                'class' => 'application.components.ApiStdModelBehavior',
                'publicApiProperties' => array(
                    'id',
                    'screen_name',
                    'profile_image_url',
                    'full_name',
                    'location',
                    'points' => 'countPoints',
                    'level',
                ),
            ),
        );
    }
}

protected/controllers/UsersController.php
<?php

class UsersController extends Controller {

    public $userName;
    
    public function actionById($userId){
        $user = User::model()->find('id = :id', array(':id' => $userId));
        $this->actionView($user);
    }
    
    public function actionByName($userName){
        $user = User::model()->find('screen_name LIKE :userName', array(':userName' => $userName));
        $this->actionView($user);
    }

    public function actionView($user) {
        if ($user) {
            $this->userName = $user->screen_name;
            $criteria = new CDbCriteria();
            $criteria->condition = 'ach_approved_date IS NOT NULL AND status = ' . UserAchievement::STATUS_APPROVED;
            $achievedCount = Achievement::model()->achievedByUser($user)->public()->count($criteria);
            $achievedPages = new CPagination($achievedCount);
            $achievedPages->pageVar = 'achPage';
            $achievedPages->pageSize = 10;
            $achievedPages->params = $_GET;
            $criteria->order = 'ach_date DESC';
            unset($achievedPages->params['addedPage']);
            $achievedPages->applyLimit($criteria);
            $achievedList = Achievement::model()->achievedByUser($user)->public()->findAll($criteria);

            $criteria2 = new CDbCriteria();
            $addedCount = Achievement::model()->addedByUser($user)->public()->count($criteria2);
            $addedPages = new CPagination($addedCount);
            $addedPages->pageVar = 'addedPage';
            $addedPages->pageSize = 10;
            $addedPages->params = $_GET;
            $criteria2->order = 'ins_date DESC';
            unset($addedPages->params['achPage']);
            $addedPages->applyLimit($criteria2);
            $addedList = Achievement::model()->addedByUser($user)->public()->findAll($criteria2);

            $activeTab = 'achievedList';
            if (!empty($_GET['addedPage'])) {
                $activeTab = 'addedList';
            }

            $this->render('view', array(
                'user' => $user,
                'viewUser' => User::model()->findByPk(Yii::app()->user->getId()),
                'achievedList' => $achievedList,
                'achievedPages' => $achievedPages,
                'achievedCount' => $achievedCount,
                'addedList' => $addedList,
                'addedPages' => $addedPages,
                'addedCount' => $addedCount,
                'activeTab' => $activeTab,
            ));
        } else {
            throw new CHttpException(404, 'Такой пользователь не найден.');
        }
    }

    public function actionInstallRoles() {

        if (Yii::app()->user->getModel()->external_id_twi != '115622071'){
            throw new CHttpException(403,'Forbidden');
        }
        
        $auth = Yii::app()->authManager;

        //сбрасываем все существующие правила
        $auth->clearAll();
        
        $task = $auth->createTask('userManage', 'управление пользователями');
        $auth->createOperation('grantModeration', 'сделать модератором');
        $auth->createOperation('revokeModeration', 'отобрать модераторорство');
        $auth->createOperation('banUser', 'заблокировать пользователя');
        $task->addChild('grantModeration');
        $task->addChild('revokeModeration');
        $task->addChild('banUser');
        
        $task = $auth->createTask('approveAchieve', 'подтверждение достижения');
        $auth->createOperation('approve', 'принять');
        $auth->createOperation('reject', 'отклонить');
        $task->addChild('approve');
        $task->addChild('reject');
        
        $auth->createOperation('addAchievement', 'добавить достижение');
        $auth->createOperation('deleteAnyAchievement', 'удалить любое достижение');
        
        
        $bizRule='return Yii::app()->user->checkAccess("deleteAnyAchievement") 
            || (Yii::app()->user->id==$params["achievement"]->author_id && $params["achievement"]->isAbleToSafeDeleted());';
        $auth->createOperation('deleteAchievement', 'удалить достижение', $bizRule);
        
        $auth->createRole('guest');
        
        $role = $auth->createRole('user');
        $role->addChild('addAchievement');
        $role->addChild('deleteAchievement');
        
        $role = $auth->createRole('moderator');
        $role->addChild('user');
        $role->addChild('approveAchieve');
        
        $role = $auth->createRole('admin');
        $role->addChild('moderator');
        $role->addChild('userManage');
        $auth->createOperation('approveMyAchieve', 'подтверждать свои достижения');
        $role->addChild('approveMyAchieve');
        $role->addChild('deleteAnyAchievement');
        
        //связываем пользователя с ролью
        //$auth->assign('admin', 2);
        
        $auth->save();
        
        echo 'Done.';
    }
    
    public function actionTop(){
        $list = User::getTopList();
        
        $this->render('top', array(
            'users'=>$list
                ));
    }

    public function actionBan(){
        if (!Yii::app()->user->checkAccess('banUser')) {
            throw new CHttpException(403, 'Forbidden');
        }
        $model = User::model()->findByPk($_REQUEST['userid']);
        
        if ($model && !empty($_POST['confirm'])){
            $model->ban();
            $this->redirect(Yii::app()->homeUrl);
        }
        
        $this->render('confirmBan', array('model'=>$model));
    }
    
    public function actionBanned(){
        if (Yii::app()->user->getModel()->banned) {
            unset(Yii::app()->session['oauth_token'], Yii::app()->session['oauth_token_secret']);
            Yii::app()->user->logout();
            $this->render('banned');
        } else {
            $this->redirect(Yii::app()->homeUrl);
        }
    }
    
    public function actionApps(){
        if (!Yii::app()->user->isGuest){
            
            $models = Yii::app()->user->getModel()->userApps(
                    array('condition'=>'grant_status = :st', 
                        'params'=>array(':st'=>UserApp::GRANT_STATUS_GRANTED)
                        ));
            
            $myApps = AppOAuth::model()->findAll('app_owner_user_id=:uid', array(':uid'=>Yii::app()->user->getId()));
            
            $this->render('apps', array(
                'models'=>$models,
                'myApps'=>$myApps,
                ));
            
        } else {
            $this->redirect('/login/index');
        }
    }
    
    public function actionRevokeApp(){
        $appId = $_GET['appId'];
        if ($appId){
            Yii::app()->user->getModel()->revokeApp($appId);
            Yii::app()->user->setFlash('success', '<strong>Приложению убран доступ!</strong>.');
            $this->redirect(array('users/apps'));
        }
    }
}

protected/views/users/apps.php
<?php
/* @var $this UsersController */
/* @var $models UserApp */

$this->pageTitle = Yii::app()->name . ' - Приложения';
?>
<h3>Список сторонних приложений, которым вы предоставили доступ</h3>

<?php
$this->widget('bootstrap.widgets.TbAlert', array(
    'alerts' => array('success' => array('block' => true, 'fade' => true, 'closeText' => '&times;')),
));
?>

<?php if (count($models)) { ?>

<table class="table">
    
    <tr>
        <th>Название</th>
        <th>Дата предоставления доступа</th>
        <th></th>
    </tr>
        
    <?php foreach ($models as $model) { ?>
    <tr>
        <td><?=CHtml::encode($model->app->app_title)?></td>
        <td><?=$model->grant_date?></td>
        <td><?=CHtml::link('убрать доступ', array('users/revokeApp', 'appId'=>$model->client_id), array('class'=>'btn btn-danger'))?></td>
    </tr>
    <?php } ?>
    
</table>

<?php } else {  ?>

<em>Вы не предоставили доступ еще ни одному стороннеу приложению.</em>

<?php } ?>


<?php if (count($myApps)) { ?>
<h3>Мои приложения</h3>
<table class="table">
    
    <tr>
        <th>Название</th>
        <th>Дата создания</th>
        <th></th>
    </tr>
        
    <?php foreach ($myApps as $model) { ?>
    <tr>
        <td><?=CHtml::encode($model->app_title)?></td>
        <td><?=$model->created_at?></td>
        <td><?=CHtml::link('редактировать', array('dev/EditApp/'.$model->client_id), array('class'=>'btn'))?></td>
    </tr>
    <?php } ?>
    
</table>

<?php } ?>

protected/views/users/banned.php
<h2>Вы заблокированы.</h2>
Для выяснения причин можете написать в Твиттер <a href="https://twitter.com/LiveLevelNet">@Livelevel.net</a>.

protected/views/users/confirmBan.php
<?php 
/* @var $model User */
?>
<h2>Действительно заблокировать?</h2>
<?php $this->beginWidget('bootstrap.widgets.TbActiveForm'); ?>
<?php $this->widget('bootstrap.widgets.TbButton', array('buttonType' => 'submit', 'label' => 'Да, заблокировать', 'htmlOptions' => array('class' => 'btn-danger', 'name'=>'confirm', 'value'=>'yes'))); ?>
<?php $this->endWidget(); ?>

<?php $this->widget('widgets.user.UserWidget', array('model' => $model));?>

protected/views/users/top.php
<?php 
/* @var $users User[]*/
$this->pageTitle = Yii::app()->name . ' - Топ пользователей';
?>
<h2>Топ пользователей</h2>
<?php if (count($users)) { ?>
    <table class="table">
        <tr>
            <th>#</th>
            <th>Пользователь</th>
            <th>Уровень</th>
            <th>Очки</th>
            <th>Добавил достижений</th>
            <th>Выполнил достижений</th>
            <th>Дата регистрации</th>
        </tr>

        <?php $i = 0;
        foreach ($users as $user) {
            $i++; ?>
            <tr>
                <td><?= $i ?></td>
                <td><?php $this->widget('widgets.user.UserWidget', array( 'model' => $user, 'showLevel' => false));?></td>
                <td><?php echo (int)$user->level;?></td>
                <td><?php echo (int)$user->countPoints();?></td>
                <td><?php echo count($user->achievementsAuthor);?></td>
                <td><?php echo $user->countAchievedAndProoved();?></td>
                <td><?php echo Yii::app()->dateFormatter->formatDateTime(CDateTimeParser::parse($user->ins_date), 'medium', null); ?></td>
            </tr>
    <?php } ?>
    </table>
<?php } else { ?>
<em>Список ещё пуст. Он ждёт своих чемпионов. Может вы станете им? Получите первый уровень!</em>
<?php } ?>

protected/views/users/view.php
<?php
/* @var $user User */
$this->pageTitle = Yii::app()->name . ' - Профиль пользователя '. CHtml::encode($user->screen_name);
?>
<div class="row">
    <div class="span6 well">
        <div class="row">
            <div class="span1">
                <a href="<?= CHtml::encode($user->getExternalProfileUrl()) ?>" class="thumbnail">
                    <img src="<?= CHtml::encode($user->profile_image_url) ?>" alt="<?= CHtml::encode($user->screen_name) ?>"></a>
            </div>
            <div class="span5">
                <p><?= CHtml::encode($user->screen_name) ?>
                <?php if (Yii::app()->user->checkAccess('banUser') && !$user->banned) { ?>
                    <a href="<?=Yii::app()->createUrl('/users/ban', array('userid'=>$user->id))?>" class="btn btn-danger btn-mini">Заблокировать</a>
                <?php } ?>
                </p>
                <p><strong><?= CHtml::encode($user->full_name) ?></strong>, уровень <?=$user->level?></p>
                <span class="badge badge-warning">Достижений добавил: <?= $addedCount ?></span> 
                <span class=" badge badge-info">Достижений выполнено и подтверждено: <?= $achievedCount ?></span>
                <span class=" badge badge-success">Очков: <?= (int)$user->countPoints() ?></span>
            </div>
        </div>
    </div>
</div>

<ul class="nav nav-tabs">
    <li class="<?php if ($activeTab == 'achievedList') echo 'active'; ?>"><a href="#achievedList" data-toggle="tab">Выполеннные и подтверждённые достижения</a></li>
    <li class="<?php if ($activeTab == 'addedList') echo 'active'; ?>"><a href="#addedList" data-toggle="tab">Добавленные достижения</a></li>
</ul>

<div class="tab-content">
    <div class="tab-pane <?php if ($activeTab == 'achievedList') echo 'active'; ?>" id="achievedList">
        <?php if (count($achievedList)) { ?>
            <?php foreach ($achievedList as $ach) { ?>
                <?php $this->widget('widgets.achievement.AchWidget', array('model' => $ach, 'user' => $user)); ?>
            <?php } ?>

            <?php
            $this->widget('CLinkPager', array(
                'pages' => $achievedPages,
            ))
            ?>
        <? } else { ?>
            <em>Таких ещё нет.</em>
        <?php } ?>
    </div>

    <div class="tab-pane <?php if ($activeTab == 'addedList') echo 'active'; ?>" id="addedList">
        <?php if (count($addedList)) { ?>
            <?php foreach ($addedList as $ach) { ?>
                <?php $this->widget('widgets.achievement.AchWidget', array('model' => $ach, 'user' => $viewUser)); ?>
            <?php } ?>

            <?php
            $this->widget('CLinkPager', array(
                'pages' => $addedPages,
            ))
            ?>

        <?php } else { ?>
            <em>Таких ещё нет.</em>
        <?php } ?>
    </div>
</div>